# Generated by Django 6.0.4 on 2026-05-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='year',
            field=models.IntegerField(db_index=True),
        ),
    ]
