# Generated by Django 6.0.4 on 2026-05-04 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0001_initial'),
        ('questions', '0002_alter_question_difficulty_alter_question_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userattempt',
            options={'ordering': ['-attempted_at']},
        ),
        migrations.AlterUniqueTogether(
            name='userattempt',
            unique_together={('user', 'question')},
        ),
    ]
